# Generated by Django 2.1.1 on 2018-09-09 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import newsletter.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Newsletter title')),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(help_text='Sender e-mail', max_length=254, verbose_name='E-mail')),
                ('sender', models.CharField(help_text='Sender name', max_length=100, verbose_name='Sender')),
                ('visible', models.BooleanField(db_index=True, default=True, verbose_name='Visible')),
                ('send_html', models.BooleanField(default=True, help_text='Whether or not to send HTML versions of e-mails.', verbose_name='Send html')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('activation_code', models.CharField(default=newsletter.utils.make_activation_code, max_length=40)),
                ('subscribed', models.BooleanField(db_index=True, default=False)),
                ('subscribe_date', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed', models.BooleanField(db_index=True, default=False)),
                ('unsubscribe_date', models.DateTimeField(blank=True, null=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Newsletter', verbose_name='Newsletter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'email', 'newsletter')},
        ),
    ]
